version: '3.8'
services:
  mongo:
    image: mongo
    container_name: database
    command: mongod --quiet --logpath /dev/null
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/var/lib/mongodb

  service:
    image: service
    container_name: service
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    links:
      - mongo
    volumes:
      - ./:/usr/local/apps/stage
      - node_modules:/usr/local/apps/stage/node_modules

volumes:
  node_modules:
  db:
