# Base image
FROM node:alpine

# Specify working directory
WORKDIR /usr/local/apps/stage

# Install dependencies
COPY ["package.json", "./"]
RUN yarn install

# Copy project files
COPY . .

CMD ["yarn", "start"]